/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letscalculate;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class LetsCalculate extends javax.swing.JFrame {
Random r =new Random();
int a ,  b,answer;
int correct_ans=0;
int wrong_ans=0;
int totqu=0;
double answer2;
int number=10;
    /**
     * Creates new form LetsCalculate
     */
    public LetsCalculate() {
        initComponents();
        setIcon();
        btn_sum.setVisible(false);
        btn_ext.setVisible(false);
        btn_mult.setVisible(false);
        btn_comp.setVisible(false);
        ImageIcon user=new ImageIcon("C:\\Users\\Acer\\Desktop\\800px_COLOURBOX3933180.jpg");
        Image ımg=user.getImage();
        Image imgScale=ımg.getScaledInstance(lbl_photo.getWidth(),lbl_photo.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        lbl_photo.setIcon(scaledIcon);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
    }
    public void setIcon(){
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("symbol.png")));
      } 

    
    public void make_number(){
         a=r.nextInt(number);
        b=r.nextInt(number);
        
        btn_a.setText(Integer.toString(a));
        btn_b.setText(Integer.toString(b));
        
    }
    public void make_number2(){
         a=r.nextInt(number);
         for (int i = 0; i < 100; i++) {
             int c=r.nextInt(10);
             if (a%c==0 && a>=c) {
                 b=c;
                break;
             }
             
        }
        btn_a.setText(Integer.toString(a));
        btn_b.setText(Integer.toString(b));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        player = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_pname = new javax.swing.JTextField();
        btn_approve = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_coranswer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_pname = new javax.swing.JLabel();
        lbl_wrongans = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_totqu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_gamemod = new javax.swing.JLabel();
        btn_b = new javax.swing.JButton();
        btn_operation = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();
        txt_answer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_accept = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_sum = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_ext = new javax.swing.JButton();
        btn_comp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ch_easy = new javax.swing.JMenuItem();
        ch_med = new javax.swing.JMenuItem();
        ch_hard = new javax.swing.JMenuItem();
        ch_quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        player.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 14)); // NOI18N
        jLabel1.setText("Player Name");
        player.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 13, -1, -1));
        player.add(txt_pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 58, 127, -1));

        btn_approve.setText("Approve");
        btn_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_approveActionPerformed(evt);
            }
        });
        player.add(btn_approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 96, -1, -1));

        jPanel1.add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 100, 200, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ravie", 3, 14)); // NOI18N
        jLabel2.setText("Player Table");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 13, 144, -1));

        jLabel3.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel3.setText("Player Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 58, -1, 22));

        lbl_coranswer.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        lbl_coranswer.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(lbl_coranswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 98, 130, 22));

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel4.setText("Correct Answer");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 98, -1, 22));

        jLabel6.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel6.setText("Wrong Answer");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 138, -1, 22));

        lbl_pname.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        lbl_pname.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(lbl_pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 58, 110, 22));

        lbl_wrongans.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        lbl_wrongans.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_wrongans, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 138, 110, 22));

        jLabel5.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel5.setText("Game Mode ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        lbl_totqu.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        lbl_totqu.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(lbl_totqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 171, 110, 25));

        jLabel9.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabel9.setText("Total Question ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 171, -1, 25));

        lbl_gamemod.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        lbl_gamemod.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(lbl_gamemod, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 100, -1, 240));

        btn_b.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jPanel1.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 375, 161, 155));

        btn_operation.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jPanel1.add(btn_operation, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 375, 104, 155));

        btn_a.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        jPanel1.add(btn_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 375, 161, 155));
        jPanel1.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 561, 263, -1));

        jLabel7.setFont(new java.awt.Font("Ravie", 3, 14)); // NOI18N
        jLabel7.setText("Answer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 561, -1, -1));

        btn_accept.setText("Accept");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 560, -1, -1));

        jButton5.setText("New Game");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 256, -1, -1));

        btn_sum.setText("+");
        btn_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 256, -1, -1));

        btn_mult.setText("x");
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 299, 41, -1));

        btn_ext.setText("-");
        btn_ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_extActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 256, 38, -1));

        btn_comp.setText("/");
        btn_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compActionPerformed(evt);
            }
        });
        jPanel1.add(btn_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 299, 38, -1));

        jLabel8.setFont(new java.awt.Font("Ravie", 3, 36)); // NOI18N
        jLabel8.setText("LETS CALCULATE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, -1, 71));
        jPanel1.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Options");

        ch_easy.setText("Easy (0-10)");
        ch_easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_easyActionPerformed(evt);
            }
        });
        jMenu1.add(ch_easy);

        ch_med.setText("Medium (0-20)");
        ch_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_medActionPerformed(evt);
            }
        });
        jMenu1.add(ch_med);

        ch_hard.setText("Hard (0-30)");
        ch_hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_hardActionPerformed(evt);
            }
        });
        jMenu1.add(ch_hard);

        ch_quit.setText("Quıt");
        ch_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_quitActionPerformed(evt);
            }
        });
        jMenu1.add(ch_quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About Us");

        jMenuItem1.setText("About Me");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Version 1.0");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Warning");

        jMenuItem2.setText("Warning");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_approveActionPerformed
        lbl_pname.setText(txt_pname.getText());
        txt_pname.setText("");
    }//GEN-LAST:event_btn_approveActionPerformed

    private void btn_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumActionPerformed
        make_number();
    
       btn_operation.setText("+");
       btn_ext.setVisible(false);
       btn_mult.setVisible(false);
       btn_comp.setVisible(false);  
      
       
    }//GEN-LAST:event_btn_sumActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (lbl_pname.getText().equals("") || lbl_gamemod.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Pls Enter The Player Name and Choose The Game Mod !");
        }
        else{
            
                btn_sum.setVisible(true);
        btn_ext.setVisible(true);
        btn_mult.setVisible(true);
        btn_comp.setVisible(true);      
        totqu=0;
        correct_ans=0;
        wrong_ans=0;
        lbl_wrongans.setText("0");
        lbl_coranswer.setText("0");
        lbl_totqu.setText("0");
        }
        
    
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        if (btn_operation.getText().equals("+")) {
            answer=a+b;
        }
        else if(btn_operation.getText().equals("-")){
            answer=a-b;
        }
        else if(btn_operation.getText().equals("x")){
            answer=a*b;
        }
        else if(btn_operation.getText().equals("/")){
            answer=(int) ((double)a/b);
        }
        if (answer==Integer.parseInt(txt_answer.getText())) {
            correct_ans++;
        }
        
        else{
            wrong_ans++;
        }
        
        txt_answer.setText("");
        btn_a.setText("");
        btn_b.setText("");
        lbl_coranswer.setText(Integer.toString(correct_ans));
        lbl_wrongans.setText(Integer.toString(wrong_ans));
        make_number();
        totqu++;
        lbl_totqu.setText(Integer.toString(totqu));
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_extActionPerformed
       make_number();
       btn_operation.setText("-");
       btn_sum.setVisible(false);
       btn_mult.setVisible(false);
       btn_comp.setVisible(false); 
    }//GEN-LAST:event_btn_extActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
       make_number();
       btn_operation.setText("x");
       btn_ext.setVisible(false);
       btn_sum.setVisible(false);
       btn_comp.setVisible(false); 
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compActionPerformed
       make_number2();
       btn_operation.setText("/");
       btn_ext.setVisible(false);
       btn_sum.setVisible(false);
       btn_mult.setVisible(false); 
        
    }//GEN-LAST:event_btn_compActionPerformed

    private void ch_easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_easyActionPerformed
      number=10;
      JOptionPane.showMessageDialog(null,"You choose the Easy Level !");
      lbl_gamemod.setText("EASY");
    }//GEN-LAST:event_ch_easyActionPerformed

    private void ch_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_quitActionPerformed
      this.dispose();
      
    }//GEN-LAST:event_ch_quitActionPerformed

    private void ch_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_medActionPerformed
      number=20;
      JOptionPane.showMessageDialog(null,"You choose the Medium Level !");
      lbl_gamemod.setText("MEDIUM");
    }//GEN-LAST:event_ch_medActionPerformed

    private void ch_hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_hardActionPerformed
      number=30;
      JOptionPane.showMessageDialog(null,"You choose  the Hard Level !");
      lbl_gamemod.setText("HARD");
    }//GEN-LAST:event_ch_hardActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      JOptionPane.showMessageDialog(null,"I am 20 years old , My Name is Enes Sefa Erdoğan and i am a Software Engineering Student in Turkey , Enjoy it!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      JOptionPane.showMessageDialog(null,"When you play with Compartment you should write the part of integer of answer ! ") ;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetsCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetsCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetsCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetsCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetsCalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_approve;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_comp;
    private javax.swing.JButton btn_ext;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_operation;
    private javax.swing.JButton btn_sum;
    private javax.swing.JMenuItem ch_easy;
    private javax.swing.JMenuItem ch_hard;
    private javax.swing.JMenuItem ch_med;
    private javax.swing.JMenuItem ch_quit;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_coranswer;
    private javax.swing.JLabel lbl_gamemod;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_pname;
    private javax.swing.JLabel lbl_totqu;
    private javax.swing.JLabel lbl_wrongans;
    private javax.swing.JPanel player;
    private javax.swing.JTextField txt_answer;
    private javax.swing.JTextField txt_pname;
    // End of variables declaration//GEN-END:variables
}
